version: "3.8"
services:
    frontend:
        image: node:14-alpine
        depends_on:
            - api
        command: sh -c "npm install && npm run start"
        ports:
            - 3000:3000
        working_dir: /frontend
        volumes:
            - ./frontend:/frontend
    api:
        image: node:14-alpine
        depends_on:
            - postgres
            - redis
        command: sh -c "npm install && npm run ${API_START_SCRIPT}"
        environment:
            DATABASE_URL: postgres://api:pass@postgres:5432/${NODE_ENV}
            NODE_ENV: development
            PORT: 4000
            SESSION_SECRET: shhhhhh
            SALT_ROUNDS: 5
            REDIS_URL: redis://redis
        ports:
            - 4000:4000
        working_dir: /api
        volumes:
            - ./api:/api
    postgres:
        image: postgres:13.2-alpine
        ports:
            - 35432:5432
        environment: # 'psql develop -U api' to access
            POSTGRES_USER: api
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: ${NODE_ENV}
    redis:
        image: redis:6.2.1-alpine
        expose:
            - 6379
